### ISSUE TITLE
mezzanine_block contains 'South migrations'

### ISSUE THREAD

**Issue by teran-mckinney** [renyi/mezzanine-blocks#22]
Hi,

I get this error when I run syncdb. I'm using Mezzanine 4.0.1 and Django 1.8.6.

```
(venv) #$ python manage.py syncdb
/Users/teran/mezzanine/venv/lib/python2.7/site-packages/mezzanine/utils/conf.py:51: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/Users/teran/mezzanine/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app u'mezzanine_blocks' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

Has anyone else had this? Are these versions not supported?

Thank you,
Teran

**Comment by renyi** [comment]
Have you tried this https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south ?
